spring:
  application:
    name: DistributedTransactions
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20  # connection pool
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
  web:
    resources:
      add-mappings: true


logging:
  level:
    org.hibernate.SQL: ${LOG_LEVEL}
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.example.distributedtransactions: DEBUG

task-queue:
  retries: ${TASK_RETRIES}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs



